[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = [
  "NODE_OPTIONS=--experimental-require-module npx prisma generate",
  "NODE_OPTIONS=--experimental-require-module npx prisma db push --skip-generate",
  "NODE_OPTIONS=--experimental-require-module npx next build"
]

[start]
cmd = "NODE_OPTIONS=--experimental-require-module npm start"
